PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX :       <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/aggregates/manifest#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX dawgt:  <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX sparql: <http://www.w3.org/ns/sparql#>

SELECT ?test ?type ?name ?feature ?comment ?approval ?approvedBy ?query ?data ?result
WHERE {
    ?test rdf:type mf:CSVResultFormatTest .
    ?test rdf:type ?type
    OPTIONAL {?test mf:name ?name }.
    OPTIONAL {?test mf:feature ?feature }.
    OPTIONAL {?test rdfs:comment ?comment }.
    OPTIONAL {?test dawgt:approval ?approval }.
    OPTIONAL {?test dawgt:approvedBy  ?approvedBy }.
    ?test mf:action ?action .
    ?action qt:data ?data .
    ?action qt:query ?query .
    ?test mf:result ?result .
}
