PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mf:      <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX dawgt:   <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX qt:      <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX ut:      <http://www.w3.org/2009/sparql/tests/test-update#>
PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
PREFIX ent:     <http://www.w3.org/ns/entailment/RDF>
PREFIX rs:      <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>

SELECT ?test ?type ?name ?feature ?comment ?approval ?approvedBy ?query ?data ?result ?regime ?action ?resultData ?request ?graphData ?graph ?resultGraph ?label ?resultLabel
WHERE {
    ?test rdf:type mf:UpdateEvaluationTest .
    ?test rdf:type ?type .
    OPTIONAL {?test mf:name ?name }.
    OPTIONAL {?test rdfs:comment ?comment }.
    OPTIONAL {?test dawgt:approval ?approval }.
    OPTIONAL {?test dawgt:approvedBy  ?approvedBy }.
    ?test mf:action ?action .
    ?action ut:request ?request .
    ?action ut:data ?data .
    OPTIONAL {
        ?action ut:graphData ?graphData .
        ?graphData ut:graph ?graph .
        ?graphData rdfs:label ?label .
    }.
    ?test mf:result ?result .
    ?result ut:data ?resultData .
    OPTIONAL {
        ?result ut:graphData ?graphData .
        ?graphData ut:graph ?resultGraph .
        ?graphData rdfs:label ?resultLabel .
    }.
}