PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mf:      <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX dawgt:   <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX qt:      <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX ut:      <http://www.w3.org/2009/sparql/tests/test-update#>
PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
PREFIX ent:     <http://www.w3.org/ns/entailment/RDF>
PREFIX rs:      <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>

SELECT ?type ?name ?query ?result ?data ?test ?feature ?comment ?approval ?approvedBy ?regime ?actionGraphData # ?graphStore ?graphLabel ?graphData ?actionGraphStore ?actionGraphLabel ?actionGraphData
WHERE {
    {
        ?test rdf:type mf:PositiveSyntaxTest11 .
    }
    UNION
    {
        ?test rdf:type mf:NegativeSyntaxTest11 .
    }
    UNION
    {
        ?test rdf:type mf:PositiveUpdateSyntaxTest11 .
    }
    UNION
    {
        ?test rdf:type mf:NegativeUpdateSyntaxTest11 .
    }
    ?test rdf:type ?iftype
    BIND(
        IF(STRENDS( STR(?iftype), "PositiveSyntaxTest11" ), "PositiveSyntaxTest11",
        IF(STRENDS( STR(?iftype), "NegativeSyntaxTest11" ), "NegativeSyntaxTest11",
        IF(STRENDS( STR(?iftype), "PositiveUpdateSyntaxTest11" ), "PositiveUpdateSyntaxTest11",
        IF(STRENDS( STR(?iftype), "NegativeUpdateSyntaxTest11" ), "NegativeUpdateSyntaxTest11",
    ""))))
    AS ?type).
    OPTIONAL {?test mf:name ?name }.
    OPTIONAL {?test dawgt:approval ?approval }.
    OPTIONAL {?test dawgt:approvedBy ?approvedBy }.
    ?test mf:action ?query .
}